$env:TWILIO_ACCOUNT_SID = "$env:TWILIO_ACCOUNT_SID"
$env:TWILIO_AUTH_TOKEN = "$env:TWILIO_AUTH_TOKEN"
$env:TWILIO_WHATSAPP_FROM = "whatsapp:+14155238886"
$env:DATABASE_URL = "$env:DATABASE_URL"
$env:TWILIO_VALIDATE_SIGNATURE = "false"
$env:WHATSAPP_PUBLIC_BASE_URL = ""
$env:WHATSAPP_SILENT_REPLY = "false"
$env:WHATSAPP_AUTO_ACK_TEXT = "Got it — processing your message."
$env:WHATSAPP_AUTO_ACK_VOICE = "Got your voice note — transcribing now."
$env:VOICE_APP_UPLOAD_URL = "http://localhost:5000/upload"
$env:WHATSAPP_EVENTS_DIR = "$PSScriptRoot\local-data\events"
$env:WHATSAPP_MEDIA_DIR = "$PSScriptRoot\local-data\media"
$env:WHATSAPP_TMP_DIR = "$PSScriptRoot\local-data\tmp"

Write-Host "Starting whatsapp-ingest on http://localhost:5011"
Write-Host "Twilio signature validation: DISABLED (local dev)"
Write-Host ""

python "$PSScriptRoot\app.py"
