-- Dutch first names (male)
INSERT INTO name_dictionary (value, category, locale) VALUES
    ('Thomas',  'first_name', 'nl'),
    ('Daan',    'first_name', 'nl'),
    ('Sem',     'first_name', 'nl'),
    ('Lars',    'first_name', 'nl'),
    ('Tim',     'first_name', 'nl'),
    ('Jan',     'first_name', 'nl'),
    ('Rob',     'first_name', 'nl'),
    ('Erik',    'first_name', 'nl'),
    ('Mark',    'first_name', 'nl'),
    ('Peter',   'first_name', 'nl'),
    ('Paul',    'first_name', 'nl'),
    ('Hans',    'first_name', 'nl'),
    ('Frank',   'first_name', 'nl'),
    ('Arjan',   'first_name', 'nl'),
    ('Bas',     'first_name', 'nl'),
    ('Bram',    'first_name', 'nl'),
    ('David',   'first_name', 'nl'),
    ('Floris',  'first_name', 'nl'),
    ('Geert',   'first_name', 'nl'),
    ('Ivo',     'first_name', 'nl'),
    ('Joep',    'first_name', 'nl'),
    ('Karel',   'first_name', 'nl'),
    ('Leon',    'first_name', 'nl'),
    ('Maarten', 'first_name', 'nl'),
    ('Niels',   'first_name', 'nl'),
    ('Pieter',  'first_name', 'nl'),
    ('Remco',   'first_name', 'nl'),
    ('Stefan',  'first_name', 'nl'),
    ('Thijs',   'first_name', 'nl'),
    ('Victor',  'first_name', 'nl'),
    ('Wout',    'first_name', 'nl'),
    ('Xander',  'first_name', 'nl'),
    ('Yannick', 'first_name', 'nl'),
    ('Harm',    'first_name', 'nl')
ON CONFLICT (value, category) DO NOTHING;

-- Dutch first names (female) 
INSERT INTO name_dictionary (value, category, locale) VALUES
    ('Emma',    'first_name', 'nl'),
    ('Sophie',  'first_name', 'nl'),
    ('Lotte',   'first_name', 'nl'),
    ('Noor',    'first_name', 'nl'),
    ('Eva',     'first_name', 'nl'),
    ('Lisa',    'first_name', 'nl'),
    ('Sara',    'first_name', 'nl'),
    ('Laura',   'first_name', 'nl'),
    ('Mia',     'first_name', 'nl'),
    ('Nina',    'first_name', 'nl'),
    ('Eline',   'first_name', 'nl'),
    ('Kim',     'first_name', 'nl'),
    ('Iris',    'first_name', 'nl'),
    ('Fleur',   'first_name', 'nl'),
    ('Roos',    'first_name', 'nl'),
    ('Hannah',  'first_name', 'nl'),
    ('Amber',   'first_name', 'nl'),
    ('Anna',    'first_name', 'nl'),
    ('Julia',   'first_name', 'nl'),
    ('Britt',   'first_name', 'nl'),
    ('Diana',   'first_name', 'nl'),
    ('Femke',   'first_name', 'nl'),
    ('Hilde',   'first_name', 'nl'),
    ('Ilse',    'first_name', 'nl'),
    ('Jana',    'first_name', 'nl'),
    ('Karen',   'first_name', 'nl'),
    ('Linda',   'first_name', 'nl'),
    ('Maaike',  'first_name', 'nl'),
    ('Naomi',   'first_name', 'nl'),
    ('Sandra',  'first_name', 'nl'),
    ('Tess',    'first_name', 'nl'),
    ('Vera',    'first_name', 'nl'),
    ('Yvonne',  'first_name', 'nl')
ON CONFLICT (value, category) DO NOTHING;

-- Dutch tussenvoegels
INSERT INTO name_dictionary (value, category, locale) VALUES
    ('aan',    'tussenvoegsel', 'nl'),
    ('af',     'tussenvoegsel', 'nl'),
    ('bij',    'tussenvoegsel', 'nl'),
    ('den',    'tussenvoegsel', 'nl'),
    ('der',    'tussenvoegsel', 'nl'),
    ('de',     'tussenvoegsel', 'nl'),
    ('d',     'tussenvoegsel', 'nl'),
    ('het',    'tussenvoegsel', 'nl'),
    ('in',     'tussenvoegsel', 'nl'),
    ('onder',  'tussenvoegsel', 'nl'),
    ('op',     'tussenvoegsel', 'nl'),
    ('over',   'tussenvoegsel', 'nl'),
    ('''s ',    'tussenvoegsel', 'nl'),
    ('''t ',    'tussenvoegsel', 'nl'),
    ('ten ',    'tussenvoegsel', 'nl'),
    ('ter ',    'tussenvoegsel', 'nl'),
    ('te ',     'tussenvoegsel', 'nl'),
    ('tot ',    'tussenvoegsel', 'nl'),
    ('uit ',    'tussenvoegsel', 'nl'),
    ('uijt ',   'tussenvoegsel', 'nl'),
    ('van ',    'tussenvoegsel', 'nl'),
    ('ver ',    'tussenvoegsel', 'nl'),
    ('voor ',   'tussenvoegsel', 'nl')
ON CONFLICT (value, category) DO NOTHING;