-- Name dictionary and profanity tables.
-- Runs after schema.sql (alphabetical order: schema < seed).

CREATE TABLE IF NOT EXISTS name_dictionary (
    id        SERIAL PRIMARY KEY,
    value     VARCHAR(100) NOT NULL,
    category  VARCHAR(20)  NOT NULL CHECK (category IN ('first_name', 'tussenvoegel')),
    locale    VARCHAR(10),
    UNIQUE (value, category)
);

CREATE TABLE IF NOT EXISTS profanity_terms (
    id      SERIAL PRIMARY KEY,
    term    VARCHAR(100) NOT NULL UNIQUE,
    locale  VARCHAR(10)
);

CREATE INDEX IF NOT EXISTS idx_name_dict_category ON name_dictionary (category);
CREATE INDEX IF NOT EXISTS idx_name_dict_locale   ON name_dictionary (locale);

-- â”€â”€ Dutch first names (male) â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
INSERT INTO name_dictionary (value, category, locale) VALUES
    ('Thomas',  'first_name', 'nl'),
    ('Daan',    'first_name', 'nl'),
    ('Sem',     'first_name', 'nl'),
    ('Lars',    'first_name', 'nl'),
    ('Tim',     'first_name', 'nl'),
    ('Jan',     'first_name', 'nl'),
    ('Rob',     'first_name', 'nl'),
    ('Erik',    'first_name', 'nl'),
    ('Mark',    'first_name', 'nl'),
    ('Peter',   'first_name', 'nl'),
    ('Paul',    'first_name', 'nl'),
    ('Hans',    'first_name', 'nl'),
    ('Frank',   'first_name', 'nl'),
    ('Arjan',   'first_name', 'nl'),
    ('Bas',     'first_name', 'nl'),
    ('Bram',    'first_name', 'nl'),
    ('David',   'first_name', 'nl'),
    ('Floris',  'first_name', 'nl'),
    ('Geert',   'first_name', 'nl'),
    ('Ivo',     'first_name', 'nl'),
    ('Joep',    'first_name', 'nl'),
    ('Karel',   'first_name', 'nl'),
    ('Leon',    'first_name', 'nl'),
    ('Maarten', 'first_name', 'nl'),
    ('Niels',   'first_name', 'nl'),
    ('Pieter',  'first_name', 'nl'),
    ('Remco',   'first_name', 'nl'),
    ('Stefan',  'first_name', 'nl'),
    ('Thijs',   'first_name', 'nl'),
    ('Victor',  'first_name', 'nl'),
    ('Wout',    'first_name', 'nl'),
    ('Xander',  'first_name', 'nl'),
    ('Yannick', 'first_name', 'nl'),
    ('Harm',    'first_name', 'nl')
ON CONFLICT (value, category) DO NOTHING;

-- â”€â”€ Dutch first names (female) â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
INSERT INTO name_dictionary (value, category, locale) VALUES
    ('Emma',    'first_name', 'nl'),
    ('Sophie',  'first_name', 'nl'),
    ('Lotte',   'first_name', 'nl'),
    ('Noor',    'first_name', 'nl'),
    ('Eva',     'first_name', 'nl'),
    ('Lisa',    'first_name', 'nl'),
    ('Sara',    'first_name', 'nl'),
    ('Laura',   'first_name', 'nl'),
    ('Mia',     'first_name', 'nl'),
    ('Nina',    'first_name', 'nl'),
    ('Eline',   'first_name', 'nl'),
    ('Kim',     'first_name', 'nl'),
    ('Iris',    'first_name', 'nl'),
    ('Fleur',   'first_name', 'nl'),
    ('Roos',    'first_name', 'nl'),
    ('Hannah',  'first_name', 'nl'),
    ('Amber',   'first_name', 'nl'),
    ('Anna',    'first_name', 'nl'),
    ('Julia',   'first_name', 'nl'),
    ('Britt',   'first_name', 'nl'),
    ('Diana',   'first_name', 'nl'),
    ('Femke',   'first_name', 'nl'),
    ('Hilde',   'first_name', 'nl'),
    ('Ilse',    'first_name', 'nl'),
    ('Jana',    'first_name', 'nl'),
    ('Karen',   'first_name', 'nl'),
    ('Linda',   'first_name', 'nl'),
    ('Maaike',  'first_name', 'nl'),
    ('Naomi',   'first_name', 'nl'),
    ('Sandra',  'first_name', 'nl'),
    ('Tess',    'first_name', 'nl'),
    ('Vera',    'first_name', 'nl'),
    ('Yvonne',  'first_name', 'nl')
ON CONFLICT (value, category) DO NOTHING;

-- â”€â”€ Irish first names â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
INSERT INTO name_dictionary (value, category, locale) VALUES
    ('Sean',     'first_name', 'ie'),
    ('Patrick',  'first_name', 'ie'),
    ('Conor',    'first_name', 'ie'),
    ('Liam',     'first_name', 'ie'),
    ('Eoin',     'first_name', 'ie'),
    ('Brendan',  'first_name', 'ie'),
    ('Ciaran',   'first_name', 'ie'),
    ('Declan',   'first_name', 'ie'),
    ('Kieran',   'first_name', 'ie'),
    ('Tadhg',    'first_name', 'ie'),
    ('Cormac',   'first_name', 'ie'),
    ('Darragh',  'first_name', 'ie'),
    ('Fionn',    'first_name', 'ie'),
    ('Oisin',    'first_name', 'ie'),
    ('Ruairi',   'first_name', 'ie'),
    ('Ciara',    'first_name', 'ie'),
    ('Aoife',    'first_name', 'ie'),
    ('Niamh',    'first_name', 'ie'),
    ('Caitlin',  'first_name', 'ie'),
    ('Aisling',  'first_name', 'ie'),
    ('Deirdre',  'first_name', 'ie'),
    ('Eimear',   'first_name', 'ie'),
    ('Grainne',  'first_name', 'ie'),
    ('Maeve',    'first_name', 'ie'),
    ('Orla',     'first_name', 'ie'),
    ('Roisin',   'first_name', 'ie'),
    ('Saoirse',  'first_name', 'ie'),
    ('Siobhan',  'first_name', 'ie'),
    ('Muireann', 'first_name', 'ie'),
    ('Clodagh',  'first_name', 'ie')
ON CONFLICT (value, category) DO NOTHING;

-- â”€â”€ Dutch tussenvoegels (name particles) â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
INSERT INTO name_dictionary (value, category, locale) VALUES
    ('van',     'tussenvoegel', 'nl'),
    ('de',      'tussenvoegel', 'nl'),
    ('den',     'tussenvoegel', 'nl'),
    ('der',     'tussenvoegel', 'nl'),
    ('het',     'tussenvoegel', 'nl'),
    ('van de',  'tussenvoegel', 'nl'),
    ('van den', 'tussenvoegel', 'nl'),
    ('van der', 'tussenvoegel', 'nl'),
    ('van het', 'tussenvoegel', 'nl'),
    ('in de',   'tussenvoegel', 'nl'),
    ('in het',  'tussenvoegel', 'nl'),
    ('op de',   'tussenvoegel', 'nl'),
    ('op den',  'tussenvoegel', 'nl'),
    ('ter',     'tussenvoegel', 'nl'),
    ('ten',     'tussenvoegel', 'nl'),
    ('te',      'tussenvoegel', 'nl'),
    ('''t',     'tussenvoegel', 'nl'),
    ('af',      'tussenvoegel', 'nl'),
    ('bij',     'tussenvoegel', 'nl'),
    ('uit',     'tussenvoegel', 'nl'),
    ('voor',    'tussenvoegel', 'nl')
ON CONFLICT (value, category) DO NOTHING;

-- Profanity terms (sourced from words.json)
INSERT INTO profanity_terms (term, locale) VALUES
    ('2 girls 1 cup', NULL),
    ('2g1c', NULL),
    ('4r5e', NULL),
    ('5h1t', NULL),
    ('5hit', NULL),
    ('5ht', NULL),
    ('@$$', NULL),
    ('a s s', NULL),
    ('a s shole', NULL),
    ('a55', NULL),
    ('a55hole', NULL),
    ('a_s_s', NULL),
    ('abbo', NULL),
    ('abeed', NULL),
    ('abuse', NULL),
    ('acrotomophilia', NULL),
    ('africoon', NULL),
    ('ahole', NULL),
    ('alabama hot pocket', NULL),
    ('alaskan pipeline', NULL),
    ('alligator bait', NULL),
    ('alligatorbait', NULL),
    ('amcik', NULL),
    ('anal', NULL),
    ('analannie', NULL),
    ('analprobe', NULL),
    ('analsex', NULL),
    ('andskota', NULL),
    ('anilingus', NULL),
    ('anus', NULL),
    ('apeshit', NULL),
    ('ar5e', NULL),
    ('arabush', NULL),
    ('arabushs', NULL),
    ('areola', NULL),
    ('areole', NULL),
    ('argie', NULL),
    ('armo', NULL),
    ('armos', NULL),
    ('arrse', NULL),
    ('arschloch', NULL),
    ('arse', NULL),
    ('arsehole', NULL),
    ('aryan', NULL),
    ('ash0le', NULL),
    ('ash0les', NULL),
    ('asholes', NULL),
    ('ass monkey', NULL),
    ('ass', NULL),
    ('ass-fucker', NULL),
    ('ass-hat', NULL),
    ('ass-pirate', NULL),
    ('assbag', NULL),
    ('assbagger', NULL),
    ('assbandit', NULL),
    ('assbang', NULL),
    ('assbanged', NULL),
    ('assbanger', NULL),
    ('assbangs', NULL),
    ('assbite', NULL),
    ('assblaster', NULL),
    ('assclown', NULL),
    ('asscock', NULL),
    ('asscowboy', NULL),
    ('asscracker', NULL),
    ('asses', NULL),
    ('assface', NULL),
    ('assfuck', NULL),
    ('assfucker', NULL),
    ('assfukka', NULL),
    ('assgoblin', NULL),
    ('assh0le', NULL),
    ('assh0lez', NULL),
    ('asshat', NULL),
    ('asshead', NULL),
    ('assho1e', NULL),
    ('asshole', NULL),
    ('assholes', NULL),
    ('assholz', NULL),
    ('asshopper', NULL),
    ('asshore', NULL),
    ('assjacker', NULL),
    ('assjockey', NULL),
    ('asskiss', NULL),
    ('asskisser', NULL),
    ('assklown', NULL),
    ('asslick', NULL),
    ('asslicker', NULL),
    ('asslover', NULL),
    ('assman', NULL),
    ('assmaster', NULL),
    ('assmonkey', NULL),
    ('assmunch', NULL),
    ('assmuncher', NULL),
    ('assnigger', NULL),
    ('asspacker', NULL),
    ('asspirate', NULL),
    ('asspuppies', NULL),
    ('assrammer', NULL),
    ('assranger', NULL),
    ('assshit', NULL),
    ('assshole', NULL),
    ('asssucker', NULL),
    ('asswad', NULL),
    ('asswhole', NULL),
    ('asswhore', NULL),
    ('asswipe', NULL),
    ('asswipes', NULL),
    ('auto erotic', NULL),
    ('autoerotic', NULL),
    ('ayir', NULL),
    ('azazel', NULL),
    ('azz', NULL),
    ('azzhole', NULL),
    ('b a s t a r d', NULL),
    ('b i t c h', NULL),
    ('b o o b', NULL),
    ('b!+ch', NULL),
    ('b!tch', NULL),
    ('b!tchin', NULL),
    ('b*tch', NULL),
    ('b00b', NULL),
    ('b00bies', NULL),
    ('b00biez', NULL),
    ('b00bs', NULL),
    ('b00bz', NULL),
    ('b17ch', NULL),
    ('b1tch', NULL),
    ('b7ch', NULL),
    ('babeland', NULL),
    ('babes', NULL),
    ('baby batter', NULL),
    ('baby juice', NULL),
    ('backdoorman', NULL),
    ('badfuck', NULL),
    ('ball gag', NULL),
    ('ball gravy', NULL),
    ('ball kicking', NULL),
    ('ball licking', NULL),
    ('ball sack', NULL),
    ('ball sucking', NULL),
    ('ballbag', NULL),
    ('balllicker', NULL),
    ('ballsack', NULL),
    ('bampot', NULL),
    ('bangbro', NULL),
    ('bangbros', NULL),
    ('bangbus', NULL),
    ('bareback', NULL),
    ('barely legal', NULL),
    ('barelylegal', NULL),
    ('barenaked', NULL),
    ('barface', NULL),
    ('barfface', NULL),
    ('bassterd', NULL),
    ('bassterds', NULL),
    ('bastard', NULL),
    ('bastardo', NULL),
    ('bastards', NULL),
    ('bastardz', NULL),
    ('basterds', NULL),
    ('basterdz', NULL),
    ('bastinado', NULL),
    ('bazongas', NULL),
    ('bazooms', NULL),
    ('bbw', NULL),
    ('bdsm', NULL),
    ('beaner', NULL),
    ('beaners', NULL),
    ('beaney', NULL),
    ('beaneys', NULL),
    ('beardedclam', NULL),
    ('beastality', NULL),
    ('beastial', NULL),
    ('beastiality', NULL),
    ('beastility', NULL),
    ('beatch', NULL),
    ('beatoff', NULL),
    ('beatyourmeat', NULL),
    ('beaver cleaver', NULL),
    ('beaver lips', NULL),
    ('beef curtains', NULL),
    ('beeyotch', NULL),
    ('bellend', NULL),
    ('beotch', NULL),
    ('bestial', NULL),
    ('bestiality', NULL),
    ('bi curious', NULL),
    ('bi+ch', NULL),
    ('bi7ch', NULL),
    ('biatch', NULL),
    ('bicurious', NULL),
    ('big black', NULL),
    ('big breasts', NULL),
    ('big knockers', NULL),
    ('big tits', NULL),
    ('bigass', NULL),
    ('bigbastard', NULL),
    ('bigbreasts', NULL),
    ('bigbutt', NULL),
    ('bigtits', NULL),
    ('bimbo', NULL),
    ('bimbos', NULL),
    ('bint', NULL),
    ('birdlock', NULL),
    ('bitch', NULL),
    ('bitchass', NULL),
    ('bitched', NULL),
    ('bitcher', NULL),
    ('bitchers', NULL),
    ('bitches', NULL),
    ('bitchez', NULL),
    ('bitchin', NULL),
    ('bitching', NULL),
    ('bitchslap', NULL),
    ('bitchtit', NULL),
    ('bitchy', NULL),
    ('biteme', NULL),
    ('bitties', NULL),
    ('black cock', NULL),
    ('blackcock', NULL),
    ('blackman', NULL),
    ('blacks', NULL),
    ('blonde action', NULL),
    ('blonde on blonde action', NULL),
    ('blonde on blonde', NULL),
    ('bloodclaat', NULL),
    ('blow j', NULL),
    ('blow job', NULL),
    ('blow your l', NULL),
    ('blow your load', NULL),
    ('blowjob', NULL),
    ('blowjobs', NULL),
    ('blue waffle', NULL),
    ('bluegum', NULL),
    ('bluegums', NULL),
    ('blumpkin', NULL),
    ('bo ob', NULL),
    ('bo obs', NULL),
    ('boang', NULL),
    ('boche', NULL),
    ('boches', NULL),
    ('boffing', NULL),
    ('bogan', NULL),
    ('bohunk', NULL),
    ('boink', NULL),
    ('boiolas', NULL),
    ('bollick', NULL),
    ('bollock', NULL),
    ('bollocks', NULL),
    ('bollok', NULL),
    ('bollox', NULL),
    ('bombers', NULL),
    ('bomd', NULL),
    ('bondage', NULL),
    ('boned', NULL),
    ('boner', NULL),
    ('boners', NULL),
    ('bong', NULL),
    ('boong', NULL),
    ('boonga', NULL),
    ('boongas', NULL),
    ('boongs', NULL),
    ('boonie', NULL),
    ('boonies', NULL),
    ('booobs', NULL),
    ('boooobs', NULL),
    ('booooobs', NULL),
    ('booooooobs', NULL),
    ('bootee', NULL),
    ('bootlip', NULL),
    ('bootlips', NULL),
    ('boozer', NULL),
    ('bosch', NULL),
    ('bosche', NULL),
    ('bosches', NULL),
    ('boschs', NULL),
    ('bosomy', NULL),
    ('bounty bar', NULL),
    ('bounty bars', NULL),
    ('bountybar', NULL),
    ('brea5t', NULL),
    ('breastjob', NULL),
    ('breastlover', NULL),
    ('breastman', NULL),
    ('brown shower', NULL),
    ('brown showers', NULL),
    ('brunette action', NULL),
    ('btch', NULL),
    ('buceta', NULL),
    ('buddhahead', NULL),
    ('buddhaheads', NULL),
    ('buffies', NULL),
    ('bugger', NULL),
    ('buggered', NULL),
    ('buggery', NULL),
    ('bukake', NULL),
    ('bukkake', NULL),
    ('bullcrap', NULL),
    ('bulldike', NULL),
    ('bulldyke', NULL),
    ('bullet vibe', NULL),
    ('bullshit', NULL),
    ('bullshits', NULL),
    ('bullshitted', NULL),
    ('bullturds', NULL),
    ('bumblefuck', NULL),
    ('bumfuck', NULL),
    ('bung hole', NULL),
    ('bung', NULL),
    ('bunga', NULL),
    ('bungas', NULL),
    ('bunghole', NULL),
    ('bunny fucker', NULL),
    ('burr head', NULL),
    ('burr heads', NULL),
    ('burrhead', NULL),
    ('burrheads', NULL),
    ('butchbabes', NULL),
    ('butchdike', NULL),
    ('butchdyke', NULL),
    ('butt plug', NULL),
    ('butt-pirate', NULL),
    ('buttbang', NULL),
    ('buttcheeks', NULL),
    ('buttface', NULL),
    ('buttfuck', NULL),
    ('buttfucker', NULL),
    ('buttfuckers', NULL),
    ('butthead', NULL),
    ('butthole', NULL),
    ('buttman', NULL),
    ('buttmuch', NULL),
    ('buttmunch', NULL),
    ('buttmuncher', NULL),
    ('buttpirate', NULL),
    ('buttplug', NULL),
    ('buttstain', NULL),
    ('buttwipe', NULL),
    ('byatch', NULL),
    ('c u n t', NULL),
    ('c-0-c-k', NULL),
    ('c-o-c-k', NULL),
    ('c-u-n-t', NULL),
    ('c.0.c.k', NULL),
    ('c.o.c.k.', NULL),
    ('c.u.n.t', NULL),
    ('c0ck', NULL),
    ('c0cks', NULL),
    ('c0cksucker', NULL),
    ('c0k', NULL),
    ('cabron', NULL),
    ('caca', NULL),
    ('cacker', NULL),
    ('cahone', NULL),
    ('camel jockey', NULL),
    ('camel jockeys', NULL),
    ('camel toe', NULL),
    ('cameljockey', NULL),
    ('cameltoe', NULL),
    ('camgirl', NULL),
    ('camslut', NULL),
    ('camwhore', NULL),
    ('carpet muncher', NULL),
    ('carpetmuncher', NULL),
    ('carruth', NULL),
    ('cawk', NULL),
    ('cawks', NULL),
    ('cazzo', NULL),
    ('chav', NULL),
    ('cheese eating surrender monkey', NULL),
    ('cheese eating surrender monkies', NULL),
    ('cheeseeating surrender monkey', NULL),
    ('cheeseeating surrender monkies', NULL),
    ('cheesehead', NULL),
    ('cheeseheads', NULL),
    ('cherrypopper', NULL),
    ('chickslick', NULL),
    ('china swede', NULL),
    ('china swedes', NULL),
    ('chinaman', NULL),
    ('chinamen', NULL),
    ('chinaswede', NULL),
    ('chinaswedes', NULL),
    ('chinc', NULL),
    ('chincs', NULL),
    ('ching chong', NULL),
    ('ching chongs', NULL),
    ('chinga', NULL),
    ('chingchong', NULL),
    ('chingchongs', NULL),
    ('chink', NULL),
    ('chinks', NULL),
    ('chinky', NULL),
    ('choad', NULL),
    ('chocolate rosebuds', NULL),
    ('chode', NULL),
    ('chodes', NULL),
    ('chonkies', NULL),
    ('chonky', NULL),
    ('chonkys', NULL),
    ('chraa', NULL),
    ('christ killer', NULL),
    ('christ killers', NULL),
    ('chug', NULL),
    ('chugs', NULL),
    ('chuj', NULL),
    ('chunger', NULL),
    ('chungers', NULL),
    ('chunkies', NULL),
    ('chunkys', NULL),
    ('cipa', NULL),
    ('circlejerk', NULL),
    ('cl1t', NULL),
    ('clamdigger', NULL),
    ('clamdiver', NULL),
    ('clamps', NULL),
    ('clansman', NULL),
    ('clansmen', NULL),
    ('clanswoman', NULL),
    ('clanswomen', NULL),
    ('cleveland steamer', NULL),
    ('clit', NULL),
    ('clitface', NULL),
    ('clitfuck', NULL),
    ('clitoris', NULL),
    ('clitorus', NULL),
    ('clits', NULL),
    ('clitty', NULL),
    ('clogwog', NULL),
    ('clover clamps', NULL),
    ('clusterfuck', NULL),
    ('cnts', NULL),
    ('cntz', NULL),
    ('cnut', NULL),
    ('cocain', NULL),
    ('cocaine', NULL),
    ('cock', NULL),
    ('cock-head', NULL),
    ('cock-sucker', NULL),
    ('cockbite', NULL),
    ('cockblock', NULL),
    ('cockblocker', NULL),
    ('cockburger', NULL),
    ('cockcowboy', NULL),
    ('cockface', NULL),
    ('cockfight', NULL),
    ('cockfucker', NULL),
    ('cockhead', NULL),
    ('cockholster', NULL),
    ('cockjockey', NULL),
    ('cockknob', NULL),
    ('cockknocker', NULL),
    ('cockknoker', NULL),
    ('cocklicker', NULL),
    ('cocklover', NULL),
    ('cockmaster', NULL),
    ('cockmongler', NULL),
    ('cockmongruel', NULL),
    ('cockmonkey', NULL),
    ('cockmunch', NULL),
    ('cockmuncher', NULL),
    ('cocknob', NULL),
    ('cocknose', NULL),
    ('cocknugget', NULL),
    ('cockqueen', NULL),
    ('cockrider', NULL),
    ('cocks', NULL),
    ('cockshit', NULL),
    ('cocksman', NULL),
    ('cocksmith', NULL),
    ('cocksmoker', NULL),
    ('cocksucer', NULL),
    ('cocksuck', NULL),
    ('cocksucked', NULL),
    ('cocksucker', NULL),
    ('cocksucking', NULL),
    ('cocksucks', NULL),
    ('cocksuka', NULL),
    ('cocksukka', NULL),
    ('cocktease', NULL),
    ('cocky', NULL),
    ('cohee', NULL),
    ('coital', NULL),
    ('coitus', NULL),
    ('cok', NULL),
    ('cokmuncher', NULL),
    ('coksucka', NULL),
    ('condom', NULL),
    ('coochie', NULL),
    ('coochy', NULL),
    ('coolie', NULL),
    ('coolies', NULL),
    ('cooly', NULL),
    ('coon ass', NULL),
    ('coon asses', NULL),
    ('coonass', NULL),
    ('coonasses', NULL),
    ('coondog', NULL),
    ('coons', NULL),
    ('cooter', NULL),
    ('coprolagnia', NULL),
    ('coprophilia', NULL),
    ('copulate', NULL),
    ('corksucker', NULL),
    ('cornhole', NULL),
    ('cra5h', NULL),
    ('crackcocain', NULL),
    ('crackpipe', NULL),
    ('crackwhore', NULL),
    ('crap', NULL),
    ('crapola', NULL),
    ('crapper', NULL),
    ('crappy', NULL),
    ('creampie', NULL),
    ('crotchjockey', NULL),
    ('crotchmonkey', NULL),
    ('crotchrot', NULL),
    ('cuck', NULL),
    ('cum face', NULL),
    ('cum licker', NULL),
    ('cum', NULL),
    ('cumbubble', NULL),
    ('cumdumpster', NULL),
    ('cumfest', NULL),
    ('cumguzzler', NULL),
    ('cuming', NULL),
    ('cumjockey', NULL),
    ('cumlickr', NULL),
    ('cumm', NULL),
    ('cummer', NULL),
    ('cummin', NULL),
    ('cumming', NULL),
    ('cumquat', NULL),
    ('cumqueen', NULL),
    ('cums', NULL),
    ('cumshot', NULL),
    ('cumshots', NULL),
    ('cumslut', NULL),
    ('cumstain', NULL),
    ('cumsucker', NULL),
    ('cumtart', NULL),
    ('cunilingus', NULL),
    ('cunillingus', NULL),
    ('cunn', NULL),
    ('cunnie', NULL),
    ('cunnilingus', NULL),
    ('cunntt', NULL),
    ('cunny', NULL),
    ('cunt', NULL),
    ('cunteyed', NULL),
    ('cuntface', NULL),
    ('cuntfuck', NULL),
    ('cuntfucker', NULL),
    ('cunthole', NULL),
    ('cunthunter', NULL),
    ('cuntlick', NULL),
    ('cuntlicker', NULL),
    ('cuntlicking', NULL),
    ('cuntrag', NULL),
    ('cunts', NULL),
    ('cuntslut', NULL),
    ('cuntsucker', NULL),
    ('cuntz', NULL),
    ('curry muncher', NULL),
    ('curry munchers', NULL),
    ('currymuncher', NULL),
    ('currymunchers', NULL),
    ('cushi', NULL),
    ('cushis', NULL),
    ('cyalis', NULL),
    ('cyberfuc', NULL),
    ('cyberfuck', NULL),
    ('cyberfucked', NULL),
    ('cyberfucker', NULL),
    ('cyberfuckers', NULL),
    ('cyberfucking', NULL),
    ('cybersex', NULL),
    ('cyberslimer', NULL),
    ('d0ng', NULL),
    ('d0uch3', NULL),
    ('d0uche', NULL),
    ('d1ck', NULL),
    ('d1ld0', NULL),
    ('d1ldo', NULL),
    ('d4mn', NULL),
    ('dago', NULL),
    ('dagos', NULL),
    ('dahmer', NULL),
    ('damm', NULL),
    ('dammit', NULL),
    ('damn', NULL),
    ('damnit', NULL),
    ('darkey', NULL),
    ('darkeys', NULL),
    ('darkie', NULL),
    ('darkies', NULL),
    ('darky', NULL),
    ('date rape', NULL),
    ('daterape', NULL),
    ('datnigga', NULL),
    ('dawgie style', NULL),
    ('dawgie-style', NULL),
    ('daygo', NULL),
    ('deapthroat', NULL),
    ('deep throat', NULL),
    ('deep throating', NULL),
    ('deepaction', NULL),
    ('deepthroat', NULL),
    ('deepthroating', NULL),
    ('defecate', NULL),
    ('deggo', NULL),
    ('dego', NULL),
    ('degos', NULL),
    ('dendrophilia', NULL),
    ('destroyyourpussy', NULL),
    ('deth', NULL),
    ('diaper daddy', NULL),
    ('diaper head', NULL),
    ('diaper heads', NULL),
    ('diaperdaddy', NULL),
    ('diaperhead', NULL),
    ('diaperheads', NULL),
    ('dick pic', NULL),
    ('dick', NULL),
    ('dick-ish', NULL),
    ('dickbag', NULL),
    ('dickbeater', NULL),
    ('dickbeaters', NULL),
    ('dickbrain', NULL),
    ('dickdipper', NULL),
    ('dickface', NULL),
    ('dickflipper', NULL),
    ('dickforbrains', NULL),
    ('dickfuck', NULL),
    ('dickhead', NULL),
    ('dickheads', NULL),
    ('dickhole', NULL),
    ('dickish', NULL),
    ('dickjuice', NULL),
    ('dickless', NULL),
    ('dicklick', NULL),
    ('dicklicker', NULL),
    ('dickman', NULL),
    ('dickmilk', NULL),
    ('dickmonger', NULL),
    ('dickpic', NULL),
    ('dickripper', NULL),
    ('dicks', NULL),
    ('dicksipper', NULL),
    ('dickslap', NULL),
    ('dickslicker', NULL),
    ('dicksucker', NULL),
    ('dickwad', NULL),
    ('dickweasel', NULL),
    ('dickweed', NULL),
    ('dickwhipper', NULL),
    ('dickwod', NULL),
    ('dickzipper', NULL),
    ('diddle', NULL),
    ('dike', NULL),
    ('dild0', NULL),
    ('dild0s', NULL),
    ('dildo', NULL),
    ('dildos', NULL),
    ('dilf', NULL),
    ('diligaf', NULL),
    ('dilld0', NULL),
    ('dilld0s', NULL),
    ('dillweed', NULL),
    ('dimwit', NULL),
    ('dingle', NULL),
    ('dingleberries', NULL),
    ('dingleberry', NULL),
    ('dink', NULL),
    ('dinks', NULL),
    ('dipship', NULL),
    ('dipshit', NULL),
    ('dipstick', NULL),
    ('dirsa', NULL),
    ('dirty pillows', NULL),
    ('dirty sanchez', NULL),
    ('dix', NULL),
    ('dixiedike', NULL),
    ('dixiedyke', NULL),
    ('dlck', NULL),
    ('dog style', NULL),
    ('dog-fucker', NULL),
    ('doggie style', NULL),
    ('doggie', NULL),
    ('doggie-style', NULL),
    ('doggiestyle', NULL),
    ('doggin', NULL),
    ('dogging', NULL),
    ('doggy style', NULL),
    ('doggy-style', NULL),
    ('doggystyle', NULL),
    ('dolcett', NULL),
    ('dominatricks', NULL),
    ('dominatrics', NULL),
    ('dominatrix', NULL),
    ('dommes', NULL),
    ('dong', NULL),
    ('donkey punch', NULL),
    ('donkeypunch', NULL),
    ('donkeyribber', NULL),
    ('doochbag', NULL),
    ('doodoo', NULL),
    ('doofus', NULL),
    ('dookie', NULL),
    ('doosh', NULL),
    ('dot head', NULL),
    ('dot heads', NULL),
    ('dothead', NULL),
    ('dotheads', NULL),
    ('double dong', NULL),
    ('double penetration', NULL),
    ('doubledong', NULL),
    ('doublepenetration', NULL),
    ('douch3', NULL),
    ('douche bag', NULL),
    ('douche', NULL),
    ('douche-fag', NULL),
    ('douchebag', NULL),
    ('douchebags', NULL),
    ('douchewaffle', NULL),
    ('douchey', NULL),
    ('dp action', NULL),
    ('dpaction', NULL),
    ('dragqueen', NULL),
    ('dragqween', NULL),
    ('dripdick', NULL),
    ('dry hump', NULL),
    ('dryhump', NULL),
    ('duche', NULL),
    ('dudette', NULL),
    ('dumass', NULL),
    ('dumb ass', NULL),
    ('dumbass', NULL),
    ('dumbasses', NULL),
    ('dumbbitch', NULL),
    ('dumbfuck', NULL),
    ('dumbshit', NULL),
    ('dumshit', NULL),
    ('dune coon', NULL),
    ('dune coons', NULL),
    ('dupa', NULL),
    ('dvda', NULL),
    ('dyefly', NULL),
    ('dyke', NULL),
    ('dykes', NULL),
    ('dziwka', NULL),
    ('earotics', NULL),
    ('easyslut', NULL),
    ('eat my ass', NULL),
    ('eat my', NULL),
    ('eatadick', NULL),
    ('eatballs', NULL),
    ('eathairpie', NULL),
    ('eatme', NULL),
    ('eatmyass', NULL),
    ('eatpussy', NULL),
    ('ecchi', NULL),
    ('ejackulate', NULL),
    ('ejakulate', NULL),
    ('ekrem', NULL),
    ('ekto', NULL),
    ('enculer', NULL),
    ('enema', NULL),
    ('erection', NULL),
    ('ero', NULL),
    ('erotic', NULL),
    ('erotism', NULL),
    ('esqua', NULL),
    ('essohbee', NULL),
    ('ethical slut', NULL),
    ('evl', NULL),
    ('excrement', NULL),
    ('exkwew', NULL),
    ('extacy', NULL),
    ('extasy', NULL),
    ('f u c k e r', NULL),
    ('f u c k e', NULL),
    ('f u c k', NULL),
    ('f u k', NULL),
    ('f*ck', NULL),
    ('f-u-c-k', NULL),
    ('f.u.c.k', NULL),
    ('f4nny', NULL),
    ('f_u_c_k', NULL),
    ('facefucker', NULL),
    ('fack', NULL),
    ('faeces', NULL),
    ('faen', NULL),
    ('fag', NULL),
    ('fag1t', NULL),
    ('fagbag', NULL),
    ('faget', NULL),
    ('fagfucker', NULL),
    ('fagg', NULL),
    ('fagg1t', NULL),
    ('fagged', NULL),
    ('fagging', NULL),
    ('faggit', NULL),
    ('faggitt', NULL),
    ('faggot', NULL),
    ('faggotcock', NULL),
    ('faggs', NULL),
    ('fagit', NULL),
    ('fagot', NULL),
    ('fagots', NULL),
    ('fags', NULL),
    ('fagt', NULL),
    ('fagtard', NULL),
    ('fagz', NULL),
    ('faig', NULL),
    ('faigs', NULL),
    ('faigt', NULL),
    ('fanculo', NULL),
    ('fannybandit', NULL),
    ('fannyflaps', NULL),
    ('fannyfucker', NULL),
    ('fanyy', NULL),
    ('fartknocker', NULL),
    ('fastfuck', NULL),
    ('fatah', NULL),
    ('fatfuck', NULL),
    ('fatfucker', NULL),
    ('fatso', NULL),
    ('fck', NULL),
    ('fckcum', NULL),
    ('fckd', NULL),
    ('fcuk', NULL),
    ('fcuker', NULL),
    ('fcuking', NULL),
    ('fecal', NULL),
    ('feck', NULL),
    ('fecker', NULL),
    ('feg', NULL),
    ('felatio', NULL),
    ('felch', NULL),
    ('felcher', NULL),
    ('felching', NULL),
    ('fellate', NULL),
    ('fellatio', NULL),
    ('feltch', NULL),
    ('feltcher', NULL),
    ('feltching', NULL),
    ('female squirting', NULL),
    ('femalesquirtin', NULL),
    ('femalesquirting', NULL),
    ('femdom', NULL),
    ('fetish', NULL),
    ('ficken', NULL),
    ('figging', NULL),
    ('fingerbang', NULL),
    ('fingerfood', NULL),
    ('fingerfuck', NULL),
    ('fingerfucked', NULL),
    ('fingerfucker', NULL),
    ('fingerfuckers', NULL),
    ('fingerfucking', NULL),
    ('fingerfucks', NULL),
    ('fingering', NULL),
    ('fisted', NULL),
    ('fister', NULL),
    ('fistfuck', NULL),
    ('fistfucked', NULL),
    ('fistfucker', NULL),
    ('fistfuckers', NULL),
    ('fistfucking', NULL),
    ('fistfuckings', NULL),
    ('fistfucks', NULL),
    ('fisting', NULL),
    ('fisty', NULL),
    ('fitt', NULL),
    ('flamer', NULL),
    ('flasher', NULL),
    ('flikker', NULL),
    ('flipping the bird', NULL),
    ('flogthelog', NULL),
    ('floo', NULL),
    ('floozy', NULL),
    ('flydie', NULL),
    ('flydye', NULL),
    ('foad', NULL),
    ('fok', NULL),
    ('fondle', NULL),
    ('foobar', NULL),
    ('fook', NULL),
    ('fooker', NULL),
    ('foot fetish', NULL),
    ('footaction', NULL),
    ('footfetish', NULL),
    ('footfuck', NULL),
    ('footfucker', NULL),
    ('footjob', NULL),
    ('footlicker', NULL),
    ('footstar', NULL),
    ('foreskin', NULL),
    ('forni', NULL),
    ('fornicate', NULL),
    ('fotze', NULL),
    ('foursome', NULL),
    ('fourtwenty', NULL),
    ('freakfuck', NULL),
    ('freakyfucker', NULL),
    ('freefuck', NULL),
    ('freex', NULL),
    ('frigg', NULL),
    ('frigga', NULL),
    ('frigger', NULL),
    ('frotting', NULL),
    ('fucck', NULL),
    ('fuck', NULL),
    ('fuck-tard', NULL),
    ('fucka', NULL),
    ('fuckable', NULL),
    ('fuckass', NULL),
    ('fuckbag', NULL),
    ('fuckbitch', NULL),
    ('fuckbook', NULL),
    ('fuckboy', NULL),
    ('fuckbrain', NULL),
    ('fuckbuddy', NULL),
    ('fuckbutt', NULL),
    ('fuckd', NULL),
    ('fucked', NULL),
    ('fuckedup', NULL),
    ('fucker', NULL),
    ('fuckers', NULL),
    ('fuckersucker', NULL),
    ('fuckface', NULL),
    ('fuckfest', NULL),
    ('fuckfreak', NULL),
    ('fuckfriend', NULL),
    ('fuckhead', NULL),
    ('fuckheads', NULL),
    ('fuckher', NULL),
    ('fuckhole', NULL),
    ('fuckin', NULL),
    ('fuckina', NULL),
    ('fucking', NULL),
    ('fuckingbitch', NULL),
    ('fuckings', NULL),
    ('fuckingshitmotherfucker', NULL),
    ('fuckinnuts', NULL),
    ('fuckinright', NULL),
    ('fuckit', NULL),
    ('fuckknob', NULL),
    ('fuckme', NULL),
    ('fuckmeat', NULL),
    ('fuckmehard', NULL),
    ('fuckmonkey', NULL),
    ('fuckn', NULL),
    ('fucknugget', NULL),
    ('fucknut', NULL),
    ('fucknuts', NULL),
    ('fucknutt', NULL),
    ('fucknutz', NULL),
    ('fuckoff', NULL),
    ('fuckpig', NULL),
    ('fuckpuppet', NULL),
    ('fuckr', NULL),
    ('fucks', NULL),
    ('fuckstick', NULL),
    ('fucktard', NULL),
    ('fucktards', NULL),
    ('fucktoy', NULL),
    ('fucktrophy', NULL),
    ('fuckup', NULL),
    ('fuckwad', NULL),
    ('fuckwhit', NULL),
    ('fuckwhore', NULL),
    ('fuckwit', NULL),
    ('fuckwitt', NULL),
    ('fuckyomama', NULL),
    ('fuckyou', NULL),
    ('fudge packer', NULL),
    ('fudgepacker', NULL),
    ('fugly', NULL),
    ('fuk', NULL),
    ('fukah', NULL),
    ('fuken', NULL),
    ('fuker', NULL),
    ('fukin', NULL),
    ('fuking', NULL),
    ('fukk', NULL),
    ('fukkah', NULL),
    ('fukken', NULL),
    ('fukker', NULL),
    ('fukkin', NULL),
    ('fukking', NULL),
    ('fuks', NULL),
    ('fuktard', NULL),
    ('fuktards', NULL),
    ('fukwhit', NULL),
    ('fukwit', NULL),
    ('funfuck', NULL),
    ('futanari', NULL),
    ('futanary', NULL),
    ('futkretzn', NULL),
    ('fuuck', NULL),
    ('fux', NULL),
    ('fux0r', NULL),
    ('fuxor', NULL),
    ('fvck', NULL),
    ('fvk', NULL),
    ('fxck', NULL),
    ('g-spot', NULL),
    ('g00k', NULL),
    ('gae', NULL),
    ('gai', NULL),
    ('gang bang', NULL),
    ('gangbang', NULL),
    ('gangbanged', NULL),
    ('gangbanger', NULL),
    ('gangbangs', NULL),
    ('ganja', NULL),
    ('gassyass', NULL),
    ('gator bait', NULL),
    ('gatorbait', NULL),
    ('gay sex', NULL),
    ('gayass', NULL),
    ('gaybob', NULL),
    ('gayboy', NULL),
    ('gaydo', NULL),
    ('gaygirl', NULL),
    ('gaylord', NULL),
    ('gaymuthafuckinwhore', NULL),
    ('gays', NULL),
    ('gaysex', NULL),
    ('gaytard', NULL),
    ('gaywad', NULL),
    ('gayz', NULL),
    ('geezer', NULL),
    ('geni', NULL),
    ('genital', NULL),
    ('genitals', NULL),
    ('getiton', NULL),
    ('gey', NULL),
    ('gfy', NULL),
    ('ghay', NULL),
    ('ghey', NULL),
    ('giant cock', NULL),
    ('gigolo', NULL),
    ('ginzo', NULL),
    ('ginzos', NULL),
    ('gipp', NULL),
    ('gippo', NULL),
    ('gippos', NULL),
    ('gipps', NULL),
    ('girl on top', NULL),
    ('girl on', NULL),
    ('girls gone wild', NULL),
    ('givehead', NULL),
    ('glans', NULL),
    ('glazeddonut', NULL),
    ('goatcx', NULL),
    ('goatse', NULL),
    ('god dammit', NULL),
    ('god damn', NULL),
    ('god damnit', NULL),
    ('god-dam', NULL),
    ('god-damned', NULL),
    ('godam', NULL),
    ('godammit', NULL),
    ('godamn', NULL),
    ('godamnit', NULL),
    ('goddam', NULL),
    ('goddamit', NULL),
    ('goddamm', NULL),
    ('goddammit', NULL),
    ('goddamn', NULL),
    ('goddamned', NULL),
    ('goddamnes', NULL),
    ('goddamnit', NULL),
    ('goddamnmuthafucker', NULL),
    ('godsdamn', NULL),
    ('gokkun', NULL),
    ('golden shower', NULL),
    ('goldenshower', NULL),
    ('golliwog', NULL),
    ('golliwogs', NULL),
    ('gonad', NULL),
    ('gonads', NULL),
    ('gonorrehea', NULL),
    ('gonzagas', NULL),
    ('goo girl', NULL),
    ('gooch', NULL),
    ('goodpoop', NULL),
    ('gook eye', NULL),
    ('gook eyes', NULL),
    ('gook', NULL),
    ('gookeye', NULL),
    ('gookeyes', NULL),
    ('gookies', NULL),
    ('gooks', NULL),
    ('gooky', NULL),
    ('gora', NULL),
    ('goras', NULL),
    ('goregasm', NULL),
    ('gotohell', NULL),
    ('goy', NULL),
    ('goyim', NULL),
    ('greaseball', NULL),
    ('greaseballs', NULL),
    ('groe', NULL),
    ('groid', NULL),
    ('groids', NULL),
    ('grope', NULL),
    ('grostulation', NULL),
    ('group sex', NULL),
    ('gspot', NULL),
    ('gstring', NULL),
    ('gtfo', NULL),
    ('gub', NULL),
    ('gubba', NULL),
    ('gubbas', NULL),
    ('gubs', NULL),
    ('guido', NULL),
    ('guiena', NULL),
    ('guineas', NULL),
    ('guizi', NULL),
    ('gummer', NULL),
    ('guro', NULL),
    ('gwailo', NULL),
    ('gwailos', NULL),
    ('gweilo', NULL),
    ('gweilos', NULL),
    ('gyopo', NULL),
    ('gyopos', NULL),
    ('gyp', NULL),
    ('gyped', NULL),
    ('gypo', NULL),
    ('gypos', NULL),
    ('gypp', NULL),
    ('gypped', NULL),
    ('gyppie', NULL),
    ('gyppies', NULL),
    ('gyppo', NULL),
    ('gyppos', NULL),
    ('gyppy', NULL),
    ('gyppys', NULL),
    ('gypsys', NULL),
    ('h e l l', NULL),
    ('h o m', NULL),
    ('h00r', NULL),
    ('h0ar', NULL),
    ('h0m0', NULL),
    ('h0mo', NULL),
    ('h0r', NULL),
    ('h0re', NULL),
    ('h4x0r', NULL),
    ('hadji', NULL),
    ('hadjis', NULL),
    ('hairyback', NULL),
    ('hairybacks', NULL),
    ('haji', NULL),
    ('hajis', NULL),
    ('hajji', NULL),
    ('hajjis', NULL),
    ('half breed', NULL),
    ('half caste', NULL),
    ('halfbreed', NULL),
    ('halfcaste', NULL),
    ('hamas', NULL),
    ('hamflap', NULL),
    ('hand job', NULL),
    ('handjob', NULL),
    ('haole', NULL),
    ('haoles', NULL),
    ('hapa', NULL),
    ('hard core', NULL),
    ('hardcore', NULL),
    ('hardcoresex', NULL),
    ('hardon', NULL),
    ('he11', NULL),
    ('headfuck', NULL),
    ('hebe', NULL),
    ('hebes', NULL),
    ('heeb', NULL),
    ('heebs', NULL),
    ('hells', NULL),
    ('helvete', NULL),
    ('hentai', NULL),
    ('heroin', NULL),
    ('herp', NULL),
    ('herpes', NULL),
    ('herpy', NULL),
    ('heshe', NULL),
    ('hijacking', NULL),
    ('hillbillies', NULL),
    ('hillbilly', NULL),
    ('hindoo', NULL),
    ('hiscock', NULL),
    ('hitler', NULL),
    ('hitlerism', NULL),
    ('hitlerist', NULL),
    ('hoare', NULL),
    ('hobag', NULL),
    ('hodgie', NULL),
    ('hoer', NULL),
    ('hoes', NULL),
    ('holestuffer', NULL),
    ('hom0', NULL),
    ('homo', NULL),
    ('homobangers', NULL),
    ('homodumbshit', NULL),
    ('homoey', NULL),
    ('honger', NULL),
    ('honkers', NULL),
    ('honkey', NULL),
    ('honkeys', NULL),
    ('honkie', NULL),
    ('honkies', NULL),
    ('honky', NULL),
    ('hooch', NULL),
    ('hooker', NULL),
    ('hookers', NULL),
    ('hoor', NULL),
    ('hoore', NULL),
    ('hootch', NULL),
    ('hooter', NULL),
    ('hooters', NULL),
    ('hore', NULL),
    ('hori', NULL),
    ('horis', NULL),
    ('hork', NULL),
    ('horndawg', NULL),
    ('horndog', NULL),
    ('horney', NULL),
    ('horniest', NULL),
    ('horny', NULL),
    ('horseshit', NULL),
    ('hosejob', NULL),
    ('hoser', NULL),
    ('hot carl', NULL),
    ('hot chick', NULL),
    ('hotcarl', NULL),
    ('hotdamn', NULL),
    ('hotpussy', NULL),
    ('hotsex', NULL),
    ('hottotrot', NULL),
    ('how to kill', NULL),
    ('how to murder', NULL),
    ('howtokill', NULL),
    ('howtomurdep', NULL),
    ('huevon', NULL),
    ('huge fat', NULL),
    ('hugefat', NULL),
    ('hui', NULL),
    ('hummer', NULL),
    ('humped', NULL),
    ('humper', NULL),
    ('humpher', NULL),
    ('humphim', NULL),
    ('humpin', NULL),
    ('humping', NULL),
    ('hussy', NULL),
    ('hustler', NULL),
    ('hymen', NULL),
    ('hymie', NULL),
    ('hymies', NULL),
    ('iblowu', NULL),
    ('ike', NULL),
    ('ikes', NULL),
    ('ikey', NULL),
    ('ikeymo', NULL),
    ('ikeymos', NULL),
    ('ikwe', NULL),
    ('illegals', NULL),
    ('incest', NULL),
    ('indon', NULL),
    ('indons', NULL),
    ('injun', NULL),
    ('injuns', NULL),
    ('insest', NULL),
    ('intercourse', NULL),
    ('intheass', NULL),
    ('inthebuff', NULL),
    ('israels', NULL),
    ('j3rk0ff', NULL),
    ('jack off', NULL),
    ('jack-off', NULL),
    ('jackass', NULL),
    ('jackhole', NULL),
    ('jackoff', NULL),
    ('jackshit', NULL),
    ('jacktheripper', NULL),
    ('jail bait', NULL),
    ('jailbait', NULL),
    ('jap', NULL),
    ('japcrap', NULL),
    ('japie', NULL),
    ('japies', NULL),
    ('japs', NULL),
    ('jebus', NULL),
    ('jelly donut', NULL),
    ('jerk off', NULL),
    ('jerk-off', NULL),
    ('jerk0ff', NULL),
    ('jerked', NULL),
    ('jerkoff', NULL),
    ('jerries', NULL),
    ('jerry', NULL),
    ('jewboy', NULL),
    ('jewed', NULL),
    ('jewess', NULL),
    ('jiga', NULL),
    ('jigaboo', NULL),
    ('jigaboos', NULL),
    ('jigarooni', NULL),
    ('jigaroonis', NULL),
    ('jigg', NULL),
    ('jigga', NULL),
    ('jiggabo', NULL),
    ('jiggaboo', NULL),
    ('jiggabos', NULL),
    ('jiggas', NULL),
    ('jigger', NULL),
    ('jiggerboo', NULL),
    ('jiggers', NULL),
    ('jiggs', NULL),
    ('jiggy', NULL),
    ('jigs', NULL),
    ('jihad', NULL),
    ('jijjiboo', NULL),
    ('jijjiboos', NULL),
    ('jimfish', NULL),
    ('jisim', NULL),
    ('jism', NULL),
    ('jiss', NULL),
    ('jiz', NULL),
    ('jizim', NULL),
    ('jizin', NULL),
    ('jizjuice', NULL),
    ('jizm', NULL),
    ('jizn', NULL),
    ('jizz', NULL),
    ('jizzd', NULL),
    ('jizzed', NULL),
    ('jizzim', NULL),
    ('jizzin', NULL),
    ('jizzn', NULL),
    ('jizzum', NULL),
    ('jugg', NULL),
    ('juggs', NULL),
    ('jungle bunnies', NULL),
    ('jungle bunny', NULL),
    ('junglebunny', NULL),
    ('junkie', NULL),
    ('junky', NULL),
    ('kacap', NULL),
    ('kacapas', NULL),
    ('kacaps', NULL),
    ('kaffer', NULL),
    ('kaffir', NULL),
    ('kaffre', NULL),
    ('kafir', NULL),
    ('kanake', NULL),
    ('kanker', NULL),
    ('katsap', NULL),
    ('katsaps', NULL),
    ('kawk', NULL),
    ('khokhol', NULL),
    ('khokhols', NULL),
    ('kigger', NULL),
    ('kike', NULL),
    ('kikes', NULL),
    ('kimchis', NULL),
    ('kinbaku', NULL),
    ('kink', NULL),
    ('kinkster', NULL),
    ('kinky', NULL),
    ('kinkyJesus', NULL),
    ('kissass', NULL),
    ('kiunt', NULL),
    ('kkk', NULL),
    ('klan', NULL),
    ('klansman', NULL),
    ('klansmen', NULL),
    ('klanswoman', NULL),
    ('klanswomen', NULL),
    ('klootzak', NULL),
    ('knobbing', NULL),
    ('knobead', NULL),
    ('knobed', NULL),
    ('knobend', NULL),
    ('knobhead', NULL),
    ('knobjocky', NULL),
    ('knobjokey', NULL),
    ('knobz', NULL),
    ('knockers', NULL),
    ('knulle', NULL),
    ('kock', NULL),
    ('kondum', NULL),
    ('kondums', NULL),
    ('kooch', NULL),
    ('kooches', NULL),
    ('koon', NULL),
    ('kootch', NULL),
    ('krap', NULL),
    ('krappy', NULL),
    ('kraut', NULL),
    ('krauts', NULL),
    ('kuffar', NULL),
    ('kuk', NULL),
    ('kuksuger', NULL),
    ('kum', NULL),
    ('kumbubble', NULL),
    ('kumbullbe', NULL),
    ('kumer', NULL),
    ('kummer', NULL),
    ('kumming', NULL),
    ('kums', NULL),
    ('kunilingus', NULL),
    ('kunnilingus', NULL),
    ('kunt', NULL),
    ('kunts', NULL),
    ('kuntz', NULL),
    ('kurac', NULL),
    ('kurwa', NULL),
    ('kushi', NULL),
    ('kushis', NULL),
    ('kusi', NULL),
    ('kwa', NULL),
    ('kwai lo', NULL),
    ('kwai los', NULL),
    ('kwif', NULL),
    ('kyke', NULL),
    ('kykes', NULL),
    ('kyopo', NULL),
    ('kyopos', NULL),
    ('kyrpa', NULL),
    ('l3i+ch', NULL),
    ('l3i\+ch', NULL),
    ('l3itch', NULL),
    ('labia', NULL),
    ('lapdance', NULL),
    ('leather restraint', NULL),
    ('leather straight', NULL),
    ('leatherrestraint', NULL),
    ('lebos', NULL),
    ('lech', NULL),
    ('lemon party', NULL),
    ('lemonparty', NULL),
    ('leper', NULL),
    ('lesbain', NULL),
    ('lesbayn', NULL),
    ('lesbin', NULL),
    ('lesbo', NULL),
    ('lesbos', NULL),
    ('lez', NULL),
    ('lezbe', NULL),
    ('lezbefriends', NULL),
    ('lezbian', NULL),
    ('lezbians', NULL),
    ('lezbo', NULL),
    ('lezbos', NULL),
    ('lezz', NULL),
    ('lezzian', NULL),
    ('lezzie', NULL),
    ('lezzies', NULL),
    ('lezzo', NULL),
    ('lezzy', NULL),
    ('libido', NULL),
    ('licker', NULL),
    ('licking', NULL),
    ('lickme', NULL),
    ('lilniglet', NULL),
    ('limey', NULL),
    ('limpdick', NULL),
    ('limy', NULL),
    ('lingerie', NULL),
    ('lipshits', NULL),
    ('lipshitz', NULL),
    ('livesex', NULL),
    ('loadedgun', NULL),
    ('lolita', NULL),
    ('lovebone', NULL),
    ('lovegoo', NULL),
    ('lovegun', NULL),
    ('lovejuice', NULL),
    ('lovemuscle', NULL),
    ('lovepistol', NULL),
    ('loverocket', NULL),
    ('lowlife', NULL),
    ('lsd', NULL),
    ('lubejob', NULL),
    ('lubra', NULL),
    ('lucifer', NULL),
    ('luckycammeltoe', NULL),
    ('lugan', NULL),
    ('lugans', NULL),
    ('lusting', NULL),
    ('lusty', NULL),
    ('lynch', NULL),
    ('m-fucking', NULL),
    ('m0f0', NULL),
    ('m0fo', NULL),
    ('m45terbate', NULL),
    ('ma5terb8', NULL),
    ('ma5terbate', NULL),
    ('mabuno', NULL),
    ('mabunos', NULL),
    ('macaca', NULL),
    ('macacas', NULL),
    ('mafugly', NULL),
    ('magicwand', NULL),
    ('mahbuno', NULL),
    ('mahbunos', NULL),
    ('make me come', NULL),
    ('makemecome', NULL),
    ('makemecum', NULL),
    ('male squirting', NULL),
    ('mamhoon', NULL),
    ('mams', NULL),
    ('manhater', NULL),
    ('manpaste', NULL),
    ('maricon', NULL),
    ('maricÃ³n', NULL),
    ('marijuana', NULL),
    ('masochist', NULL),
    ('masokist', NULL),
    ('massa', NULL),
    ('massterbait', NULL),
    ('masstrbait', NULL),
    ('masstrbate', NULL),
    ('mastabate', NULL),
    ('mastabater', NULL),
    ('master-bate', NULL),
    ('masterb8', NULL),
    ('masterbaiter', NULL),
    ('masterbat', NULL),
    ('masterbat3', NULL),
    ('masterbate', NULL),
    ('masterbates', NULL),
    ('masterbating', NULL),
    ('masterbation', NULL),
    ('masterbations', NULL),
    ('masterblaster', NULL),
    ('mastrabator', NULL),
    ('masturbat', NULL),
    ('masturbate', NULL),
    ('masturbating', NULL),
    ('masturbation', NULL),
    ('mattressprincess', NULL),
    ('mau mau', NULL),
    ('mau maus', NULL),
    ('maumau', NULL),
    ('maumaus', NULL),
    ('mcfagget', NULL),
    ('meatbeatter', NULL),
    ('meatrack', NULL),
    ('menage', NULL),
    ('merd', NULL),
    ('mgger', NULL),
    ('mggor', NULL),
    ('mibun', NULL),
    ('mick', NULL),
    ('mickeyfinn', NULL),
    ('mideast', NULL),
    ('mierda', NULL),
    ('milf', NULL),
    ('mindfuck', NULL),
    ('minge', NULL),
    ('minger', NULL),
    ('mo-fo', NULL),
    ('mockey', NULL),
    ('mockie', NULL),
    ('mocky', NULL),
    ('mof0', NULL),
    ('mofo', NULL),
    ('moky', NULL),
    ('molest', NULL),
    ('molestation', NULL),
    ('molester', NULL),
    ('molestor', NULL),
    ('moneyshot', NULL),
    ('mong', NULL),
    ('monkleigh', NULL),
    ('moolie', NULL),
    ('moon cricket', NULL),
    ('moon crickets', NULL),
    ('mooncricket', NULL),
    ('mooncrickets', NULL),
    ('moron', NULL),
    ('moskal', NULL),
    ('moskals', NULL),
    ('moslem', NULL),
    ('mosshead', NULL),
    ('motha fucker', NULL),
    ('motha fuker', NULL),
    ('motha fukkah', NULL),
    ('motha fukker', NULL),
    ('mothafuck', NULL),
    ('mothafucka', NULL),
    ('mothafuckas', NULL),
    ('mothafuckaz', NULL),
    ('mothafucked', NULL),
    ('mothafucker', NULL),
    ('mothafuckers', NULL),
    ('mothafuckin', NULL),
    ('mothafucking', NULL),
    ('mothafuckings', NULL),
    ('mothafucks', NULL),
    ('mother fucker', NULL),
    ('mother fukah', NULL),
    ('mother fuker', NULL),
    ('mother fukkah', NULL),
    ('mother fukker', NULL),
    ('mother-fucker', NULL),
    ('motherfuck', NULL),
    ('motherfucka', NULL),
    ('motherfucked', NULL),
    ('motherfucker', NULL),
    ('motherfuckers', NULL),
    ('motherfuckin', NULL),
    ('motherfucking', NULL),
    ('motherfuckings', NULL),
    ('motherfuckka', NULL),
    ('motherfucks', NULL),
    ('motherfvcker', NULL),
    ('motherlovebone', NULL),
    ('mothrfucker', NULL),
    ('mouliewop', NULL),
    ('mound of venus', NULL),
    ('moundofvenus', NULL),
    ('mr hands', NULL),
    ('mrhands', NULL),
    ('mtherfucker', NULL),
    ('mthrfuck', NULL),
    ('mthrfucker', NULL),
    ('mthrfucking', NULL),
    ('mtrfck', NULL),
    ('mtrfuck', NULL),
    ('mtrfucker', NULL),
    ('muff diver', NULL),
    ('muff', NULL),
    ('muffdive', NULL),
    ('muffdiver', NULL),
    ('muffdiving', NULL),
    ('muffindiver', NULL),
    ('mufflikcer', NULL),
    ('muffpuff', NULL),
    ('muie', NULL),
    ('mulatto', NULL),
    ('mulkku', NULL),
    ('muncher', NULL),
    ('munging', NULL),
    ('munt', NULL),
    ('munter', NULL),
    ('muschi', NULL),
    ('mutha fucker', NULL),
    ('mutha fukah', NULL),
    ('mutha fuker', NULL),
    ('mutha fukkah', NULL),
    ('mutha fukker', NULL),
    ('muthafecker', NULL),
    ('muthafuckaz', NULL),
    ('muthafucker', NULL),
    ('muthafuckker', NULL),
    ('muther', NULL),
    ('mutherfucker', NULL),
    ('mutherfucking', NULL),
    ('muthrfucking', NULL),
    ('mzungu', NULL),
    ('mzungus', NULL),
    ('n1gga', NULL),
    ('n1gger', NULL),
    ('n1gr', NULL),
    ('nads', NULL),
    ('naked', NULL),
    ('nambla', NULL),
    ('nastt', NULL),
    ('nastybitch', NULL),
    ('nastyho', NULL),
    ('nastyslut', NULL),
    ('nastywhore', NULL),
    ('nawashi', NULL),
    ('nazi', NULL),
    ('nazis', NULL),
    ('nazism', NULL),
    ('necro', NULL),
    ('needthedick', NULL),
    ('negres', NULL),
    ('negress', NULL),
    ('negro', NULL),
    ('negroes', NULL),
    ('negroid', NULL),
    ('negros', NULL),
    ('neonazi', NULL),
    ('nepesaurio', NULL),
    ('nig nog', NULL),
    ('nig', NULL),
    ('niga', NULL),
    ('nigar', NULL),
    ('nigars', NULL),
    ('nigas', NULL),
    ('nigers', NULL),
    ('nigette', NULL),
    ('nigettes', NULL),
    ('nigg', NULL),
    ('nigg3r', NULL),
    ('nigg4h', NULL),
    ('nigga', NULL),
    ('niggah', NULL),
    ('niggahs', NULL),
    ('niggar', NULL),
    ('niggaracci', NULL),
    ('niggard', NULL),
    ('niggarded', NULL),
    ('niggarding', NULL),
    ('niggardliness', NULL),
    ('niggardlinesss', NULL),
    ('niggardly', NULL),
    ('niggards', NULL),
    ('niggars', NULL),
    ('niggas', NULL),
    ('niggaz', NULL),
    ('nigger', NULL),
    ('niggerhead', NULL),
    ('niggerhole', NULL),
    ('niggers', NULL),
    ('niggle', NULL),
    ('niggled', NULL),
    ('niggles', NULL),
    ('nigglings', NULL),
    ('niggor', NULL),
    ('niggress', NULL),
    ('niggresses', NULL),
    ('nigguh', NULL),
    ('nigguhs', NULL),
    ('niggur', NULL),
    ('niggurs', NULL),
    ('niglet', NULL),
    ('nignog', NULL),
    ('nigor', NULL),
    ('nigors', NULL),
    ('nigr', NULL),
    ('nigra', NULL),
    ('nigras', NULL),
    ('nigre', NULL),
    ('nigres', NULL),
    ('nigress', NULL),
    ('nigs', NULL),
    ('nigur', NULL),
    ('niiger', NULL),
    ('niigr', NULL),
    ('nimphomania', NULL),
    ('nimrod', NULL),
    ('ninny', NULL),
    ('nipple', NULL),
    ('nipplering', NULL),
    ('nipples', NULL),
    ('nips', NULL),
    ('nittit', NULL),
    ('nlgger', NULL),
    ('nlggor', NULL),
    ('nob jokey', NULL),
    ('nob', NULL),
    ('nobhead', NULL),
    ('nobjocky', NULL),
    ('nobjokey', NULL),
    ('nofuckingway', NULL),
    ('nog', NULL),
    ('nookey', NULL),
    ('nookie', NULL),
    ('nooky', NULL),
    ('noonan', NULL),
    ('nooner', NULL),
    ('nsfw images', NULL),
    ('nsfw', NULL),
    ('nudger', NULL),
    ('nudie', NULL),
    ('nudies', NULL),
    ('numbnuts', NULL),
    ('nut sack', NULL),
    ('nutbutter', NULL),
    ('nutfucker', NULL),
    ('nutsack', NULL),
    ('nutten', NULL),
    ('nympho', NULL),
    ('nymphomania', NULL),
    ('o c k', NULL),
    ('octopussy', NULL),
    ('omorashi', NULL),
    ('one cup two girls', NULL),
    ('one guy one jar', NULL),
    ('one guy', NULL),
    ('one jar', NULL),
    ('ontherag', NULL),
    ('orafis', NULL),
    ('orga', NULL),
    ('orgasim', NULL),
    ('orgasim;', NULL),
    ('orgasims', NULL),
    ('orgasm', NULL),
    ('orgasmic', NULL),
    ('orgasms', NULL),
    ('orgasum', NULL),
    ('orgies', NULL),
    ('orgy', NULL),
    ('oriface', NULL),
    ('orifiss', NULL),
    ('orospu', NULL),
    ('osama', NULL),
    ('ovum', NULL),
    ('ovums', NULL),
    ('p e n i s', NULL),
    ('p i s', NULL),
    ('p u s s y', NULL),
    ('p.u.s.s.y.', NULL),
    ('p0rn', NULL),
    ('packi', NULL),
    ('packie', NULL),
    ('packy', NULL),
    ('paddy', NULL),
    ('paedophile', NULL),
    ('paki', NULL),
    ('pakie', NULL),
    ('pakis', NULL),
    ('paky', NULL),
    ('palesimian', NULL),
    ('pancake face', NULL),
    ('pancake faces', NULL),
    ('panooch', NULL),
    ('pansies', NULL),
    ('pansy', NULL),
    ('panti', NULL),
    ('pantie', NULL),
    ('panties', NULL),
    ('panty', NULL),
    ('paska', NULL),
    ('payo', NULL),
    ('pcp', NULL),
    ('pearlnecklace', NULL),
    ('pecker', NULL),
    ('peckerhead', NULL),
    ('peckerwood', NULL),
    ('pedo', NULL),
    ('pedobear', NULL),
    ('pedophile', NULL),
    ('pedophilia', NULL),
    ('pedophiliac', NULL),
    ('peeenus', NULL),
    ('peeenusss', NULL),
    ('peehole', NULL),
    ('peenus', NULL),
    ('peepee', NULL),
    ('peepshow', NULL),
    ('peepshpw', NULL),
    ('pegging', NULL),
    ('peinus', NULL),
    ('pen1s', NULL),
    ('penas', NULL),
    ('pendejo', NULL),
    ('pendy', NULL),
    ('penetrate', NULL),
    ('penetration', NULL),
    ('peni5', NULL),
    ('penial', NULL),
    ('penile', NULL),
    ('penis', NULL),
    ('penis-breath', NULL),
    ('penises', NULL),
    ('penisfucker', NULL),
    ('penisland', NULL),
    ('penislick', NULL),
    ('penislicker', NULL),
    ('penispuffer', NULL),
    ('penthouse', NULL),
    ('penus', NULL),
    ('penuus', NULL),
    ('perse', NULL),
    ('perv', NULL),
    ('perversion', NULL),
    ('peyote', NULL),
    ('phalli', NULL),
    ('phallic', NULL),
    ('phone sex', NULL),
    ('phonesex', NULL),
    ('phuc', NULL),
    ('phuck', NULL),
    ('phuk', NULL),
    ('phuked', NULL),
    ('phuker', NULL),
    ('phuking', NULL),
    ('phukked', NULL),
    ('phukker', NULL),
    ('phukking', NULL),
    ('phuks', NULL),
    ('phungky', NULL),
    ('phuq', NULL),
    ('pi55', NULL),
    ('picaninny', NULL),
    ('piccaninny', NULL),
    ('picka', NULL),
    ('pickaninnies', NULL),
    ('pickaninny', NULL),
    ('piece of shit', NULL),
    ('pieceofshit', NULL),
    ('piefke', NULL),
    ('piefkes', NULL),
    ('pierdol', NULL),
    ('pigfucker', NULL),
    ('piker', NULL),
    ('pikey', NULL),
    ('piky', NULL),
    ('pillowbiter', NULL),
    ('pillu', NULL),
    ('pimmel', NULL),
    ('pimp', NULL),
    ('pimped', NULL),
    ('pimper', NULL),
    ('pimpis', NULL),
    ('pimpjuic', NULL),
    ('pimpjuice', NULL),
    ('pimpsimp', NULL),
    ('pindick', NULL),
    ('pinko', NULL),
    ('pis', NULL),
    ('pises', NULL),
    ('pisin', NULL),
    ('pising', NULL),
    ('pisof', NULL),
    ('piss pig', NULL),
    ('piss', NULL),
    ('piss-off', NULL),
    ('pissed', NULL),
    ('pisser', NULL),
    ('pissers', NULL),
    ('pisses', NULL),
    ('pissflap', NULL),
    ('pissflaps', NULL),
    ('pisshead', NULL),
    ('pissin', NULL),
    ('pissing', NULL),
    ('pissoff', NULL),
    ('pisspig', NULL),
    ('pizda', NULL),
    ('playboy', NULL),
    ('playgirl', NULL),
    ('pleasure chest', NULL),
    ('pleasurechest', NULL),
    ('pocha', NULL),
    ('pochas', NULL),
    ('pocho', NULL),
    ('pochos', NULL),
    ('pocketpool', NULL),
    ('pohm', NULL),
    ('pohms', NULL),
    ('polac', NULL),
    ('polack', NULL),
    ('polacks', NULL),
    ('polak', NULL),
    ('pole smoker', NULL),
    ('polesmoker', NULL),
    ('pollock', NULL),
    ('pollocks', NULL),
    ('pommie grant', NULL),
    ('pommie grants', NULL),
    ('pommy', NULL),
    ('ponyplay', NULL),
    ('poof', NULL),
    ('poon', NULL),
    ('poonani', NULL),
    ('poonany', NULL),
    ('poontang', NULL),
    ('poontsee', NULL),
    ('poop chute', NULL),
    ('poopchute', NULL),
    ('pooper', NULL),
    ('pooperscooper', NULL),
    ('pooping', NULL),
    ('poorwhitetrash', NULL),
    ('popimp', NULL),
    ('porch monkey', NULL),
    ('porch monkies', NULL),
    ('porchmonkey', NULL),
    ('porn', NULL),
    ('pornflick', NULL),
    ('pornking', NULL),
    ('porno', NULL),
    ('pornography', NULL),
    ('pornos', NULL),
    ('pornprincess', NULL),
    ('pound town', NULL),
    ('poundtown', NULL),
    ('pplicker', NULL),
    ('pr0n', NULL),
    ('pr1c', NULL),
    ('pr1ck', NULL),
    ('pr1k', NULL),
    ('prairie nigger', NULL),
    ('prairie niggers', NULL),
    ('preteen', NULL),
    ('pric', NULL),
    ('prickhead', NULL),
    ('pricks', NULL),
    ('prig', NULL),
    ('prince albert piercing', NULL),
    ('pron', NULL),
    ('prostitute', NULL),
    ('pthc', NULL),
    ('pu55i', NULL),
    ('pu55y', NULL),
    ('pube', NULL),
    ('pubes', NULL),
    ('pubic', NULL),
    ('pubiclice', NULL),
    ('pubis', NULL),
    ('pudboy', NULL),
    ('pudd', NULL),
    ('puddboy', NULL),
    ('pula', NULL),
    ('punani', NULL),
    ('punanny', NULL),
    ('punany', NULL),
    ('punkass', NULL),
    ('punky', NULL),
    ('punta', NULL),
    ('puntang', NULL),
    ('purinapricness', NULL),
    ('pusies', NULL),
    ('puss', NULL),
    ('pusse', NULL),
    ('pussee', NULL),
    ('pussi', NULL),
    ('pussie', NULL),
    ('pussies', NULL),
    ('pussy', NULL),
    ('pussycat', NULL),
    ('pussydestroyer', NULL),
    ('pussyeater', NULL),
    ('pussyfart', NULL),
    ('pussyfuck', NULL),
    ('pussyfucker', NULL),
    ('pussylicker', NULL),
    ('pussylicking', NULL),
    ('pussylips', NULL),
    ('pussylover', NULL),
    ('pussypalace', NULL),
    ('pussypounder', NULL),
    ('pussys', NULL),
    ('pusy', NULL),
    ('puta', NULL),
    ('puto', NULL),
    ('puuke', NULL),
    ('puuker', NULL),
    ('qahbeh', NULL),
    ('quashie', NULL),
    ('queaf', NULL),
    ('queef', NULL),
    ('queerhole', NULL),
    ('queero', NULL),
    ('queers', NULL),
    ('queerz', NULL),
    ('quickie', NULL),
    ('quicky', NULL),
    ('quiff', NULL),
    ('quim', NULL),
    ('qweers', NULL),
    ('qweerz', NULL),
    ('qweir', NULL),
    ('r-tard', NULL),
    ('r-tards', NULL),
    ('r5e', NULL),
    ('ra8s', NULL),
    ('raghead', NULL),
    ('ragheads', NULL),
    ('rape', NULL),
    ('raped', NULL),
    ('raper', NULL),
    ('raping', NULL),
    ('rapist', NULL),
    ('rautenberg', NULL),
    ('rearend', NULL),
    ('rearentry', NULL),
    ('recktum', NULL),
    ('rectal', NULL),
    ('rectum', NULL),
    ('rectus', NULL),
    ('redleg', NULL),
    ('redlegs', NULL),
    ('redlight', NULL),
    ('redskin', NULL),
    ('redskins', NULL),
    ('reefer', NULL),
    ('reestie', NULL),
    ('reetard', NULL),
    ('reich', NULL),
    ('renob', NULL),
    ('rentafuck', NULL),
    ('rere', NULL),
    ('retard', NULL),
    ('retarded', NULL),
    ('retards', NULL),
    ('retardz', NULL),
    ('reverse cowgirl', NULL),
    ('reversecowgirl', NULL),
    ('rimjaw', NULL),
    ('rimjob', NULL),
    ('rimming', NULL),
    ('ritard', NULL),
    ('rosebuds', NULL),
    ('rosy palm and her 5 sisters', NULL),
    ('rosy palm', NULL),
    ('rosypalm', NULL),
    ('rosypalmandher5sisters', NULL),
    ('rosypalmandherefivesisters', NULL),
    ('round eyes', NULL),
    ('roundeye', NULL),
    ('rtard', NULL),
    ('rtards', NULL),
    ('rumprammer', NULL),
    ('ruski', NULL),
    ('russki', NULL),
    ('russkie', NULL),
    ('rusty trombone', NULL),
    ('rustytrombone', NULL),
    ('s h i t', NULL),
    ('s hit', NULL),
    ('s&m', NULL),
    ('s-h-1-t', NULL),
    ('s-h-i-t', NULL),
    ('s-o-b', NULL),
    ('s.h.i.t.', NULL),
    ('s.o.b.', NULL),
    ('s0b', NULL),
    ('s_h_i_t', NULL),
    ('sadis', NULL),
    ('sadism', NULL),
    ('sadist', NULL),
    ('sadom', NULL),
    ('sambo', NULL),
    ('sambos', NULL),
    ('samckdaddy', NULL),
    ('sanchez', NULL),
    ('sand nigger', NULL),
    ('sand niggers', NULL),
    ('sandm', NULL),
    ('sandnigger', NULL),
    ('santorum', NULL),
    ('sausagequeen', NULL),
    ('scag', NULL),
    ('scallywag', NULL),
    ('scank', NULL),
    ('scantily', NULL),
    ('scat', NULL),
    ('schaffer', NULL),
    ('scheiss', NULL),
    ('schizo', NULL),
    ('schlampe', NULL),
    ('schlong', NULL),
    ('schmuck', NULL),
    ('schvartse', NULL),
    ('schvartsen', NULL),
    ('schwartze', NULL),
    ('schwartzen', NULL),
    ('scissoring', NULL),
    ('screwyou', NULL),
    ('scroat', NULL),
    ('scrog', NULL),
    ('scrote', NULL),
    ('scrotum', NULL),
    ('scrud', NULL),
    ('seduce', NULL),
    ('semen', NULL),
    ('seppo', NULL),
    ('seppos', NULL),
    ('septics', NULL),
    ('sex', NULL),
    ('sexcam', NULL),
    ('sexed', NULL),
    ('sexfarm', NULL),
    ('sexhound', NULL),
    ('sexhouse', NULL),
    ('sexi', NULL),
    ('sexing', NULL),
    ('sexkitten', NULL),
    ('sexo', NULL),
    ('sexpot', NULL),
    ('sexslave', NULL),
    ('sextogo', NULL),
    ('sextoy', NULL),
    ('sextoys', NULL),
    ('sexual', NULL),
    ('sexually', NULL),
    ('sexwhore', NULL),
    ('sexx', NULL),
    ('sexxi', NULL),
    ('sexxx', NULL),
    ('sexxxi', NULL),
    ('sexxxy', NULL),
    ('sexxy', NULL),
    ('sexy', NULL),
    ('sexymoma', NULL),
    ('sexyslim', NULL),
    ('sh!+', NULL),
    ('sh!t', NULL),
    ('sh1t', NULL),
    ('sh1ter', NULL),
    ('sh1ts', NULL),
    ('sh1tter', NULL),
    ('sh1tz', NULL),
    ('shag', NULL),
    ('shagger', NULL),
    ('shaggin', NULL),
    ('shagging', NULL),
    ('shamedame', NULL),
    ('sharmuta', NULL),
    ('sharmute', NULL),
    ('shat', NULL),
    ('shav', NULL),
    ('shaved beaver', NULL),
    ('shaved pussy', NULL),
    ('shavedbeaver', NULL),
    ('shavedpussy', NULL),
    ('shawtypimp', NULL),
    ('sheeney', NULL),
    ('shemale', NULL),
    ('shhit', NULL),
    ('shi+', NULL),
    ('shibari', NULL),
    ('shibary', NULL),
    ('shinola', NULL),
    ('shipal', NULL),
    ('shit ass', NULL),
    ('shit', NULL),
    ('shit-ass', NULL),
    ('shit-bag', NULL),
    ('shit-bagger', NULL),
    ('shit-brain', NULL),
    ('shit-breath', NULL),
    ('shit-cunt', NULL),
    ('shit-dick', NULL),
    ('shit-eating', NULL),
    ('shit-face', NULL),
    ('shit-faced', NULL),
    ('shit-fit', NULL),
    ('shit-head', NULL),
    ('shit-heel', NULL),
    ('shit-hole', NULL),
    ('shit-house', NULL),
    ('shit-load', NULL),
    ('shit-pot', NULL),
    ('shit-spitter', NULL),
    ('shit-stain', NULL),
    ('shitass', NULL),
    ('shitbag', NULL),
    ('shitbagger', NULL),
    ('shitblimp', NULL),
    ('shitbrain', NULL),
    ('shitbreath', NULL),
    ('shitcan', NULL),
    ('shitcunt', NULL),
    ('shitdick', NULL),
    ('shite', NULL),
    ('shiteater', NULL),
    ('shiteating', NULL),
    ('shited', NULL),
    ('shitey', NULL),
    ('shitface', NULL),
    ('shitfaced', NULL),
    ('shitfit', NULL),
    ('shitforbrains', NULL),
    ('shitfuck', NULL),
    ('shitfucker', NULL),
    ('shitfull', NULL),
    ('shithapens', NULL),
    ('shithappens', NULL),
    ('shithead', NULL),
    ('shitheel', NULL),
    ('shithole', NULL),
    ('shithouse', NULL),
    ('shiting', NULL),
    ('shitings', NULL),
    ('shitlist', NULL),
    ('shitload', NULL),
    ('shitola', NULL),
    ('shitoutofluck', NULL),
    ('shitpot', NULL),
    ('shits', NULL),
    ('shitspitter', NULL),
    ('shitstain', NULL),
    ('shitt', NULL),
    ('shitted', NULL),
    ('shitter', NULL),
    ('shitters', NULL),
    ('shittiest', NULL),
    ('shitting', NULL),
    ('shittings', NULL),
    ('shitty', NULL),
    ('shity', NULL),
    ('shitz', NULL),
    ('shiz', NULL),
    ('shiznit', NULL),
    ('shortfuck', NULL),
    ('shota', NULL),
    ('shylock', NULL),
    ('shylocks', NULL),
    ('shyt', NULL),
    ('shyte', NULL),
    ('shytty', NULL),
    ('shyty', NULL),
    ('simp', NULL),
    ('sissy', NULL),
    ('sixsixsix', NULL),
    ('sixtynine', NULL),
    ('sixtyniner', NULL),
    ('skag', NULL),
    ('skanck', NULL),
    ('skank', NULL),
    ('skankbitch', NULL),
    ('skankee', NULL),
    ('skankey', NULL),
    ('skankfuck', NULL),
    ('skanks', NULL),
    ('skankwhore', NULL),
    ('skanky', NULL),
    ('skankybitch', NULL),
    ('skankywhore', NULL),
    ('skeet', NULL),
    ('skinflute', NULL),
    ('skribz', NULL),
    ('skullfuck', NULL),
    ('skum', NULL),
    ('skumbag', NULL),
    ('skurwysyn', NULL),
    ('skwa', NULL),
    ('skwe', NULL),
    ('slag', NULL),
    ('slanteye', NULL),
    ('slanty', NULL),
    ('slapper', NULL),
    ('sleezeball', NULL),
    ('slideitin', NULL),
    ('slimeball', NULL),
    ('slimebucket', NULL),
    ('slopehead', NULL),
    ('slopeheads', NULL),
    ('sloper', NULL),
    ('slopers', NULL),
    ('slopey', NULL),
    ('slopeys', NULL),
    ('slopies', NULL),
    ('slopy', NULL),
    ('slut', NULL),
    ('slutbag', NULL),
    ('slutbucket', NULL),
    ('slutdumper', NULL),
    ('slutkiss', NULL),
    ('sluts', NULL),
    ('slutt', NULL),
    ('slutting', NULL),
    ('slutty', NULL),
    ('slutwear', NULL),
    ('slutwhore', NULL),
    ('slutz', NULL),
    ('smackthemonkey', NULL),
    ('smeg', NULL),
    ('smegma', NULL),
    ('smut', NULL),
    ('smutty', NULL),
    ('snatchpatch', NULL),
    ('sniggered', NULL),
    ('sniggering', NULL),
    ('sniggers', NULL),
    ('snowback', NULL),
    ('snowballing', NULL),
    ('snownigger', NULL),
    ('snuff', NULL),
    ('socksucker', NULL),
    ('sodom', NULL),
    ('sodomise', NULL),
    ('sodomite', NULL),
    ('sodomize', NULL),
    ('sodomy', NULL),
    ('son of a bitch', NULL),
    ('son of a whore', NULL),
    ('son-of-a-bitch', NULL),
    ('son-of-a-whore', NULL),
    ('sonofabitch', NULL),
    ('sonofbitch', NULL),
    ('sooties', NULL),
    ('souse', NULL),
    ('soused', NULL),
    ('soyboy', NULL),
    ('spac', NULL),
    ('spaghettibender', NULL),
    ('spaghettinigger', NULL),
    ('spank', NULL),
    ('spankthemonkey', NULL),
    ('spastic', NULL),
    ('spearchucker', NULL),
    ('spearchuckers', NULL),
    ('sperm', NULL),
    ('spermacide', NULL),
    ('spermbag', NULL),
    ('spermhearder', NULL),
    ('spermherder', NULL),
    ('sphencter', NULL),
    ('spic', NULL),
    ('spick', NULL),
    ('spicks', NULL),
    ('spics', NULL),
    ('spierdalaj', NULL),
    ('spig', NULL),
    ('spigotty', NULL),
    ('spik', NULL),
    ('spiks', NULL),
    ('splittail', NULL),
    ('splooge', NULL),
    ('spludge', NULL),
    ('spooge', NULL),
    ('spread legs', NULL),
    ('spreadeagle', NULL),
    ('spunk', NULL),
    ('spunky', NULL),
    ('sqeh', NULL),
    ('squa', NULL),
    ('squarehead', NULL),
    ('squareheads', NULL),
    ('squaw', NULL),
    ('squinty', NULL),
    ('squirting', NULL),
    ('stagg', NULL),
    ('stfu', NULL),
    ('stiffy', NULL),
    ('stoned', NULL),
    ('stoner', NULL),
    ('strap on', NULL),
    ('strapon', NULL),
    ('strappado', NULL),
    ('strip club', NULL),
    ('stripclub', NULL),
    ('stroking', NULL),
    ('stuinties', NULL),
    ('stupidfuck', NULL),
    ('stupidfucker', NULL),
    ('style doggy', NULL),
    ('suckdick', NULL),
    ('sucked', NULL),
    ('sucker', NULL),
    ('sucking', NULL),
    ('suckme', NULL),
    ('suckmyass', NULL),
    ('suckmydick', NULL),
    ('suckmytit', NULL),
    ('suckoff', NULL),
    ('suicide girl', NULL),
    ('suicide girls', NULL),
    ('suicidegirl', NULL),
    ('suicidegirls', NULL),
    ('suka', NULL),
    ('sultrywoman', NULL),
    ('sultrywomen', NULL),
    ('sumofabiatch', NULL),
    ('swallower', NULL),
    ('swalow', NULL),
    ('swamp guinea', NULL),
    ('swamp guineas', NULL),
    ('swastika', NULL),
    ('syphilis', NULL),
    ('t i t', NULL),
    ('t i ts', NULL),
    ('t1t', NULL),
    ('t1tt1e5', NULL),
    ('t1tties', NULL),
    ('tacohead', NULL),
    ('tacoheads', NULL),
    ('taff', NULL),
    ('take off your', NULL),
    ('tar babies', NULL),
    ('tar baby', NULL),
    ('tarbaby', NULL),
    ('tard', NULL),
    ('taste my', NULL),
    ('tastemy', NULL),
    ('tawdry', NULL),
    ('tea bagging', NULL),
    ('teabagging', NULL),
    ('teat', NULL),
    ('teets', NULL),
    ('teez', NULL),
    ('terd', NULL),
    ('teste', NULL),
    ('testee', NULL),
    ('testes', NULL),
    ('testical', NULL),
    ('testicle', NULL),
    ('testicles', NULL),
    ('testis', NULL),
    ('thicklip', NULL),
    ('thicklips', NULL),
    ('thirdeye', NULL),
    ('thirdleg', NULL),
    ('threesome', NULL),
    ('threeway', NULL),
    ('throating', NULL),
    ('thumbzilla', NULL),
    ('thundercunt', NULL),
    ('tied up', NULL),
    ('tig ol bitties', NULL),
    ('tig old bitties', NULL),
    ('tight white', NULL),
    ('timber nigger', NULL),
    ('timber niggers', NULL),
    ('timbernigger', NULL),
    ('tit', NULL),
    ('titbitnipply', NULL),
    ('titfuck', NULL),
    ('titfucker', NULL),
    ('titfuckin', NULL),
    ('titi', NULL),
    ('titjob', NULL),
    ('titlicker', NULL),
    ('titlover', NULL),
    ('tits', NULL),
    ('titt', NULL),
    ('tittie', NULL),
    ('tittie5', NULL),
    ('tittiefucker', NULL),
    ('titties', NULL),
    ('tittis', NULL),
    ('titty', NULL),
    ('tittyfuck', NULL),
    ('tittyfucker', NULL),
    ('tittys', NULL),
    ('tittywank', NULL),
    ('titwank', NULL),
    ('tity', NULL),
    ('to murder', NULL),
    ('tongethruster', NULL),
    ('tongue in a', NULL),
    ('tongueina', NULL),
    ('tonguethrust', NULL),
    ('tonguetramp', NULL),
    ('toots', NULL),
    ('topless', NULL),
    ('tortur', NULL),
    ('torture', NULL),
    ('tosser', NULL),
    ('towel head', NULL),
    ('towel heads', NULL),
    ('towelhead', NULL),
    ('trailertrash', NULL),
    ('trannie', NULL),
    ('tranny', NULL),
    ('transsexual', NULL),
    ('transvestite', NULL),
    ('tribadism', NULL),
    ('trisexual', NULL),
    ('trois', NULL),
    ('tr00n', NULL),
    ('tr00ns', NULL),
    ('troon', NULL),
    ('troons', NULL),
    ('trots', NULL),
    ('tub girl', NULL),
    ('tubgirl', NULL),
    ('tuckahoe', NULL),
    ('tunneloflove', NULL),
    ('turd burgler', NULL),
    ('turnon', NULL),
    ('tush', NULL),
    ('tushy', NULL),
    ('tw4t', NULL),
    ('twat', NULL),
    ('twathead', NULL),
    ('twatlips', NULL),
    ('twats', NULL),
    ('twatty', NULL),
    ('twatwaffle', NULL),
    ('twink', NULL),
    ('twinkie', NULL),
    ('two girls one cup', NULL),
    ('twobitwhore', NULL),
    ('twunt', NULL),
    ('twunter', NULL),
    ('udge packer', NULL),
    ('ukrop', NULL),
    ('unclefucker', NULL),
    ('unfuckable', NULL),
    ('upskirt', NULL),
    ('uptheass', NULL),
    ('upthebutt', NULL),
    ('urethra play', NULL),
    ('urethraplay', NULL),
    ('urophilia', NULL),
    ('usama', NULL),
    ('ussys', NULL),
    ('uzi', NULL),
    ('v a g i n a', NULL),
    ('v14gra', NULL),
    ('v1gra', NULL),
    ('v4gra', NULL),
    ('va-j-j', NULL),
    ('va1jina', NULL),
    ('vag', NULL),
    ('vag1na', NULL),
    ('vagiina', NULL),
    ('vaj1na', NULL),
    ('vajina', NULL),
    ('valium', NULL),
    ('venus mound', NULL),
    ('vgra', NULL),
    ('vibr', NULL),
    ('vibrater', NULL),
    ('vibrator', NULL),
    ('vigra', NULL),
    ('violet wand', NULL),
    ('virginbreaker', NULL),
    ('vittu', NULL),
    ('vixen', NULL),
    ('vjayjay', NULL),
    ('vorarephilia', NULL),
    ('voyeurweb', NULL),
    ('voyuer', NULL),
    ('vullva', NULL),
    ('vulva', NULL),
    ('w00se', NULL),
    ('w0p', NULL),
    ('wab', NULL),
    ('wang', NULL),
    ('wank', NULL),
    ('wanker', NULL),
    ('wanking', NULL),
    ('wanky', NULL),
    ('waysted', NULL),
    ('weenie', NULL),
    ('weewee', NULL),
    ('weiner', NULL),
    ('welcher', NULL),
    ('wench', NULL),
    ('wet dream', NULL),
    ('wetb', NULL),
    ('wetback', NULL),
    ('wetbacks', NULL),
    ('wetdream', NULL),
    ('wetspot', NULL),
    ('wh00r', NULL),
    ('wh0re', NULL),
    ('wh0reface', NULL),
    ('whacker', NULL),
    ('whash', NULL),
    ('whigger', NULL),
    ('whiggers', NULL),
    ('whiskeydick', NULL),
    ('whiskydick', NULL),
    ('whit', NULL),
    ('white power', NULL),
    ('white trash', NULL),
    ('whitenigger', NULL),
    ('whitepower', NULL),
    ('whitetrash', NULL),
    ('whitey', NULL),
    ('whiteys', NULL),
    ('whities', NULL),
    ('whoar', NULL),
    ('whop', NULL),
    ('whoralicious', NULL),
    ('whore', NULL),
    ('whorealicious', NULL),
    ('whorebag', NULL),
    ('whored', NULL),
    ('whoreface', NULL),
    ('whorefucker', NULL),
    ('whorehopper', NULL),
    ('whorehouse', NULL),
    ('whores', NULL),
    ('whoring', NULL),
    ('wichser', NULL),
    ('wigga', NULL),
    ('wiggas', NULL),
    ('wigger', NULL),
    ('wiggers', NULL),
    ('willie', NULL),
    ('willies', NULL),
    ('williewanker', NULL),
    ('willy', NULL),
    ('wog', NULL),
    ('wogs', NULL),
    ('woose', NULL),
    ('wop', NULL),
    ('worldsex', NULL),
    ('wrapping men', NULL),
    ('wrinkled starfish', NULL),
    ('wtf', NULL),
    ('wuss', NULL),
    ('wuzzie', NULL),
    ('x-rated', NULL),
    ('x-rated2g1c', NULL),
    ('xkwe', NULL),
    ('xrated', NULL),
    ('xtc', NULL),
    ('xx', NULL),
    ('xxx', NULL),
    ('xxxxxx', NULL),
    ('yank', NULL),
    ('yaoi', NULL),
    ('yarpie', NULL),
    ('yarpies', NULL),
    ('yed', NULL),
    ('yellow showers', NULL),
    ('yellowman', NULL),
    ('yellowshowers', NULL),
    ('yid', NULL),
    ('yids', NULL),
    ('yiffy', NULL),
    ('yobbo', NULL),
    ('yourboobs', NULL),
    ('yourpenis', NULL),
    ('yourtits', NULL),
    ('yury', NULL),
    ('zabourah', NULL),
    ('zigabo', NULL),
    ('zigabos', NULL),
    ('zipperhead', NULL),
    ('zipperheads', NULL),
    ('zoophile', NULL),
    ('zoophilia', NULL),
    ('ðŸ–•', NULL)
ON CONFLICT (term) DO NOTHING;